UPDATE General SET FK_Pais = 1 WHERE FK_Pais = 'Algeria'
UPDATE General SET FK_Pais = 2 WHERE FK_Pais = 'Angola'
UPDATE General SET FK_Pais = 3 WHERE FK_Pais = 'Argentina'
UPDATE General SET FK_Pais = 4 WHERE FK_Pais = 'Australia'
UPDATE General SET FK_Pais = 5 WHERE FK_Pais = 'Austria'
UPDATE General SET FK_Pais = 6 WHERE FK_Pais = 'Belgium'
UPDATE General SET FK_Pais = 7 WHERE FK_Pais = 'Bolivia'
UPDATE General SET FK_Pais = 8 WHERE FK_Pais = 'Bosnia and Herzegovina'
UPDATE General SET FK_Pais = 9 WHERE FK_Pais = 'Brazil'
UPDATE General SET FK_Pais = 10 WHERE FK_Pais = 'Bulgaria'
UPDATE General SET FK_Pais = 11 WHERE FK_Pais = 'Cameroon'
UPDATE General SET FK_Pais = 12 WHERE FK_Pais = 'Canada'
UPDATE General SET FK_Pais = 13 WHERE FK_Pais = 'Chile'
UPDATE General SET FK_Pais = 14 WHERE FK_Pais = 'China PR'
UPDATE General SET FK_Pais = 15 WHERE FK_Pais = 'Colombia'
UPDATE General SET FK_Pais = 16 WHERE FK_Pais = 'Costa Rica'
UPDATE General SET FK_Pais = 17 WHERE FK_Pais = 'Croatia'
UPDATE General SET FK_Pais = 18 WHERE FK_Pais = 'Cuba'
UPDATE General SET FK_Pais = 19 WHERE FK_Pais = 'Czech Republic'
UPDATE General SET FK_Pais = 20 WHERE FK_Pais = 'Czechoslovakia'
UPDATE General SET FK_Pais = 21 WHERE FK_Pais = 'Denmark'
UPDATE General SET FK_Pais = 22 WHERE FK_Pais = 'DR Congo'
UPDATE General SET FK_Pais = 23 WHERE FK_Pais = 'Ecuador'
UPDATE General SET FK_Pais = 24 WHERE FK_Pais = 'Egypt'
UPDATE General SET FK_Pais = 25 WHERE FK_Pais = 'El Salvador'
UPDATE General SET FK_Pais = 26 WHERE FK_Pais = 'England'
UPDATE General SET FK_Pais = 27 WHERE FK_Pais = 'Finland'
UPDATE General SET FK_Pais = 28 WHERE FK_Pais = 'France'
UPDATE General SET FK_Pais = 29 WHERE FK_Pais = 'German DR'
UPDATE General SET FK_Pais = 30 WHERE FK_Pais = 'Germany'
UPDATE General SET FK_Pais = 31 WHERE FK_Pais = 'Ghana'
UPDATE General SET FK_Pais = 32 WHERE FK_Pais = 'Greece'
UPDATE General SET FK_Pais = 33 WHERE FK_Pais = 'Haiti'
UPDATE General SET FK_Pais = 34 WHERE FK_Pais = 'Honduras'
UPDATE General SET FK_Pais = 35 WHERE FK_Pais = 'Hungary'
UPDATE General SET FK_Pais = 36 WHERE FK_Pais = 'Iceland'
UPDATE General SET FK_Pais = 37 WHERE FK_Pais = 'Indonesia'
UPDATE General SET FK_Pais = 38 WHERE FK_Pais = 'Iran'
UPDATE General SET FK_Pais = 39 WHERE FK_Pais = 'Iraq'
UPDATE General SET FK_Pais = 40 WHERE FK_Pais = 'Israel'
UPDATE General SET FK_Pais = 41 WHERE FK_Pais = 'Italy'
UPDATE General SET FK_Pais = 42 WHERE FK_Pais = 'Ivory Coast'
UPDATE General SET FK_Pais = 43 WHERE FK_Pais = 'Jamaica'
UPDATE General SET FK_Pais = 44 WHERE FK_Pais = 'Japan'
UPDATE General SET FK_Pais = 45 WHERE FK_Pais = 'Kuwait'
UPDATE General SET FK_Pais = 46 WHERE FK_Pais = 'Mexico'
UPDATE General SET FK_Pais = 47 WHERE FK_Pais = 'Morocco'
UPDATE General SET FK_Pais = 48 WHERE FK_Pais = 'Netherlands'
UPDATE General SET FK_Pais = 49 WHERE FK_Pais = 'New Zealand'
UPDATE General SET FK_Pais = 50 WHERE FK_Pais = 'Nigeria'
UPDATE General SET FK_Pais = 51 WHERE FK_Pais = 'North Korea'
UPDATE General SET FK_Pais = 52 WHERE FK_Pais = 'Northern Ireland'
UPDATE General SET FK_Pais = 53 WHERE FK_Pais = 'Norway'
UPDATE General SET FK_Pais = 54 WHERE FK_Pais = 'Panama'
UPDATE General SET FK_Pais = 55 WHERE FK_Pais = 'Paraguay'
UPDATE General SET FK_Pais = 56 WHERE FK_Pais = 'Peru'
UPDATE General SET FK_Pais = 57 WHERE FK_Pais = 'Poland'
UPDATE General SET FK_Pais = 58 WHERE FK_Pais = 'Portugal'
UPDATE General SET FK_Pais = 59 WHERE FK_Pais = 'Qatar'
UPDATE General SET FK_Pais = 60 WHERE FK_Pais = 'Republic of Ireland'
UPDATE General SET FK_Pais = 61 WHERE FK_Pais = 'Romania'
UPDATE General SET FK_Pais = 62 WHERE FK_Pais = 'Russia'
UPDATE General SET FK_Pais = 63 WHERE FK_Pais = 'Saudi Arabia'
UPDATE General SET FK_Pais = 64 WHERE FK_Pais = 'Scotland'
UPDATE General SET FK_Pais = 65 WHERE FK_Pais = 'Senegal'
UPDATE General SET FK_Pais = 66 WHERE FK_Pais = 'Serbia'
UPDATE General SET FK_Pais = 67 WHERE FK_Pais = 'Slovakia'
UPDATE General SET FK_Pais = 68 WHERE FK_Pais = 'Slovenia'
UPDATE General SET FK_Pais = 69 WHERE FK_Pais = 'South Africa'
UPDATE General SET FK_Pais = 70 WHERE FK_Pais = 'South Korea'
UPDATE General SET FK_Pais = 71 WHERE FK_Pais = 'Spain'
UPDATE General SET FK_Pais = 72 WHERE FK_Pais = 'Sweden'
UPDATE General SET FK_Pais = 73 WHERE FK_Pais = 'Switzerland'
UPDATE General SET FK_Pais = 74 WHERE FK_Pais = 'Togo'
UPDATE General SET FK_Pais = 75 WHERE FK_Pais = 'Trinidad and Tobago'
UPDATE General SET FK_Pais = 76 WHERE FK_Pais = 'Tunisia'
UPDATE General SET FK_Pais = 77 WHERE FK_Pais = 'Turkey'
UPDATE General SET FK_Pais = 78 WHERE FK_Pais = 'Ukraine'
UPDATE General SET FK_Pais = 79 WHERE FK_Pais = 'United Arab Emirates'
UPDATE General SET FK_Pais = 80 WHERE FK_Pais = 'United States'
UPDATE General SET FK_Pais = 81 WHERE FK_Pais = 'Uruguay'
UPDATE General SET FK_Pais = 82 WHERE FK_Pais = 'Wales'
UPDATE General SET FK_Pais = 83 WHERE FK_Pais = 'Yugoslavia'
